name: puppeteer
description: A high-level API to control headless Chrome over the DevTools Protocol. This is a port of Puppeteer in Dart.
version: 2.24.0
homepage: https://github.com/xvrh/puppeteer-dart

platforms:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  archive: ^3.3.6
  async: ^2.10.0
  collection: ^1.17.0
  http: ^0.13.5
  logging: ^1.1.1
  path: ^1.8.2
  petitparser: ^5.1.0
  pool: ^1.5.1

dev_dependencies:
  analyzer:
  build:
  build_runner:
  crypto:
  dart_style:
  image:
  json_annotation:
  json_serializable:
  lints:
  pub_semver:
  shelf:
  shelf_router:
  shelf_static:
  shelf_web_socket:
  test:
  web_socket_channel:
  yaml:
